### ISSUE TITLE
Not working with MSO-X 3014A

### ISSUE THREAD

**Issue by markrages** [twam/scpi-scripts#1]
When I run the screen dump, the scope hangs with the message "Remote operation in progress. Please wait.".

And then I have to reboot it.

```
markrages@qountdown:~$ sudo python2 screendump.py -d USB0::2391::6056::MY53041304::0::INSTR x.png
Traceback (most recent call last):
  File "screendump.py", line 49, in <module>
    data = scope.query_binary_values(':DISPlay:DATA? PNG, COLOR', datatype='B')
  File "/usr/local/lib/python2.7/dist-packages/pyvisa/resources/messagebased.py", line 484, in query_binary_values
    offset, data_length = util.parse_ieee_block_header(block)
  File "/usr/local/lib/python2.7/dist-packages/pyvisa/util.py", line 278, in parse_ieee_block_header
    raise ValueError("Could not find hash sign (#) indicating the start of the block.")
ValueError: Could not find hash sign (#) indicating the start of the block.
```

**Comment by markrages** [comment]
Firmware is "system version 2.50.2019022736"

**Comment by twam** [comment]
Yes retested this. Runs fine with a "MSO-X 3014A" and firmware "2.50.2019022736" here on OS X.

Interesting like I seem to have a different 'PID' (USB0::2391::6054::MYxxxxxxxx::0::INSTR)
